var bankHolidays = {
  "bank_holiday": [
    {
      "poster": "assets/images/place/andaman.jpg",
      "title": "Andaman & Nicobar",
      "list": [
        {"date": "Jan 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jan 26, 2024 Friday", "holiday": "Republic Day"},
        {"date": "Jan 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Feb 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Feb 24, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Mar 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Mar 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Mar 25, 2024 Monday", "holiday": "Holi"},
        {"date": "Mar 29, 2024 Friday", "holiday": "Good Friday"},
        {"date": "Apr 10, 2024 Wednesday", "holiday": "Idul Fitr"},
        {"date": "Apr 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Apr 17, 2024 Wednesday", "holiday": "Ram Navami"},
        {"date": "Apr 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "May 11, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "May 23, 2024 Thursday", "holiday": "Buddha Purnima"},
        {"date": "May 25, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jun 8, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jun 17, 2024 Monday", "holiday": "Bakrid / Eid al Adha"},
        {"date": "Jun 22, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jul 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jul 17, 2024 Wednesday", "holiday": "Muharram"},
        {"date": "Jul 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Aug 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Aug 15, 2024 Thursday", "holiday": "Independence Day"},
        {"date": "Aug 24, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Aug 26, 2024 Monday", "holiday": "Janmashtami"},
        {"date": "Sep 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Sep 28, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Oct 2, 2024 Wednesday", "holiday": "Gandhi Jayanti"},
        {"date": "Oct 12, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Oct 13, 2024 Sunday", "holiday": "Vijaya Dashami"},
        {"date": "Oct 26, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Nov 1, 2024 Friday", "holiday": "Diwali"},
        {"date": "Nov 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Nov 15, 2024 Friday", "holiday": "Guru Nanak Jayanti"},
        {"date": "Nov 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Dec 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Dec 25, 2024 Wednesday", "holiday": "Christmas Day"},
        {"date": "Dec 28, 2024 Saturday", "holiday": "Fourth Saturday"}
      ]
    },
    {
      "poster": "assets/images/place/andhra.jpg",
      "title": "Andhra Pradesh",
      "list": [
        {"date": "Jan 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jan 15, 2024 Monday", "holiday": "Pongal"},
        {"date": "Jan 16, 2024 Tuesday", "holiday": "Kanuma Panduga"},
        {"date": "Jan 26, 2024 Friday", "holiday": "Republic Day"},
        {"date": "Jan 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Feb 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Feb 24, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Mar 8, 2024 Friday", "holiday": "Maha Shivaratri"},
        {"date": "Mar 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Mar 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Mar 25, 2024 Monday", "holiday": "Holi"},
        {"date": "Mar 29, 2024 Friday", "holiday": "Good Friday"},
        {"date": "Apr 5, 2024 Friday", "holiday": "Babu Jagjivan Ram Jayanti"},
        {"date": "Apr 9, 2024 Tuesday", "holiday": "Ugadi"},
        {"date": "Apr 10, 2024 Wednesday", "holiday": "Idul Fitr"},
        {"date": "Apr 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Apr 14, 2024 Sunday", "holiday": "Dr Ambedkar Jayanti"},
        {"date": "Apr 17, 2024 Wednesday", "holiday": "Ram Navami"},
        {"date": "Apr 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "May 11, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "May 25, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jun 8, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jun 17, 2024 Monday", "holiday": "Bakrid / Eid al Adha"},
        {"date": "Jun 22, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jul 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jul 17, 2024 Wednesday", "holiday": "Muharram"},
        {"date": "Jul 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Aug 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Aug 15, 2024 Thursday", "holiday": "Independence Day"},
        {"date": "Aug 24, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Aug 26, 2024 Monday", "holiday": "Janmashtami"},
        {"date": "Sep 7, 2024 Saturday", "holiday": "Ganesh Chaturthi"},
        {"date": "Sep 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Sep 16, 2024 Monday", "holiday": "Eid e Milad"},
        {"date": "Sep 28, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Oct 2, 2024 Wednesday", "holiday": "Gandhi Jayanti"},
        {"date": "Oct 11, 2024 Friday", "holiday": "Maha Ashtami"},
        {"date": "Oct 12, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Oct 13, 2024 Sunday", "holiday": "Vijaya Dashami"},
        {"date": "Oct 26, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Oct 31, 2024 Thursday", "holiday": "Deepavali"},
        {"date": "Nov 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Nov 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Dec 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Dec 25, 2024 Wednesday", "holiday": "Christmas Day"},
        {"date": "Dec 28, 2024 Saturday", "holiday": "Fourth Saturday"}
      ]
    },
    {
      "poster": "assets/images/place/assam.jpg",
      "title": "Assam",
      "list": [
        {"date": "Jan 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jan 15, 2024 Monday", "holiday": "Magh Bihu"},
        {"date": "Jan 26, 2024 Friday", "holiday": "Republic Day"},
        {"date": "Jan 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Feb 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Feb 24, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Mar 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Mar 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Mar 25, 2024 Monday", "holiday": "Holi"},
        {"date": "Mar 29, 2024 Friday", "holiday": "Good Friday"},
        {"date": "Apr 10, 2024 Wednesday", "holiday": "Idul Fitr"},
        {"date": "Apr 13, 2024 Saturday", "holiday": "Bohag Bihu Holiday"},
        {"date": "Apr 14, 2024 Sunday", "holiday": "Bohag Bihu"},
        {"date": "Apr 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "May 1, 2024 Wednesday", "holiday": "May Day"},
        {"date": "May 11, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "May 23, 2024 Thursday", "holiday": "Buddha Purnima"},
        {"date": "May 25, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jun 8, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jun 17, 2024 Monday", "holiday": "Bakrid / Eid al Adha"},
        {"date": "Jun 22, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jul 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jul 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Aug 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Aug 15, 2024 Thursday", "holiday": "Independence Day"},
        {"date": "Aug 24, 2024 Saturday", "holiday": "Fourth Saturday"},
        {
          "date": "Sep 5, 2024 Thursday",
          "holiday": "Tithi of Srimanta Shankardev"
        },
        {"date": "Sep 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Sep 28, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Oct 2, 2024 Wednesday", "holiday": "Gandhi Jayanti"},
        {
          "date": "Oct 12, 2024 Saturday",
          "holiday": "Maha Navami Janmostav of Srimanta Shankardev"
        },
        {"date": "Oct 13, 2024 Sunday", "holiday": "Shankardev"},
        {"date": "Oct 17, 2024 Thursday", "holiday": "Kati Bihu"},
        {"date": "Oct 26, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Nov 1, 2024 Friday", "holiday": "Diwali"},
        {"date": "Nov 7, 2024 Thursday", "holiday": "Chhath Puja"},
        {"date": "Nov 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Nov 15, 2024 Friday", "holiday": "Guru Nanak Jayanti"},
        {"date": "Nov 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Dec 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Dec 25, 2024 Wednesday", "holiday": "Christmas Day"},
        {"date": "Dec 28, 2024 Saturday", "holiday": "Fourth Saturday"}
      ]
    },
    {
      "poster": "assets/images/place/bihar.jpg",
      "title": "Bihar",
      "list": [
        {"date": "Jan 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jan 26, 2024 Friday", "holiday": "Republic Day"},
        {"date": "Jan 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Feb 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Feb 24, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Mar 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Mar 22, 2024 Friday", "holiday": "Bihar Day"},
        {"date": "Mar 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Mar 25, 2024 Monday", "holiday": "Holi"},
        {"date": "Mar 29, 2024 Friday", "holiday": "Good Friday"},
        {"date": "Apr 10, 2024 Wednesday", "holiday": "Idul Fitr"},
        {"date": "Apr 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Apr 14, 2024 Sunday", "holiday": "Dr Ambedkar Jayanti"},
        {"date": "Apr 17, 2024 Wednesday", "holiday": "Ram Navami"},
        {"date": "Apr 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "May 1, 2024 Wednesday", "holiday": "May Day"},
        {"date": "May 11, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "May 25, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jun 8, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jun 17, 2024 Monday", "holiday": "Bakrid / Eid al Adha"},
        {"date": "Jun 22, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jul 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jul 17, 2024 Wednesday", "holiday": "Muharram"},
        {"date": "Jul 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Aug 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Aug 15, 2024 Thursday", "holiday": "Independence Day"},
        {"date": "Aug 24, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Aug 26, 2024 Monday", "holiday": "Janmashtami"},
        {"date": "Sep 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Sep 28, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Oct 2, 2024 Wednesday", "holiday": "Gandhi Jayanti"},
        {"date": "Oct 12, 2024 Saturday", "holiday": "Maha Navami"},
        {"date": "Oct 13, 2024 Sunday", "holiday": "Vijaya Dashami"},
        {"date": "Oct 26, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Nov 1, 2024 Friday", "holiday": "Diwali"},
        {"date": "Nov 7, 2024 Thursday", "holiday": "Chhath Puja"},
        {"date": "Nov 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Nov 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Dec 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Dec 25, 2024 Wednesday", "holiday": "Christmas Day"},
        {"date": "Dec 28, 2024 Saturday", "holiday": "Fourth Saturday"}
      ]
    },
    {
      "poster": "assets/images/place/chandigarh.jpg",
      "title": "Chandigarh",
      "list": [
        {"date": "Jan 13, 2024 Saturday", "holiday": "Second Saturday"},
        {
          "date": "Jan 17, 2024 Wednesday",
          "holiday": "Guru Gobind Singh Jayanti"
        },
        {"date": "Jan 26, 2024 Friday", "holiday": "Republic Day"},
        {"date": "Jan 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Feb 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Feb 24, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Mar 8, 2024 Friday", "holiday": "Maha Shivaratri"},
        {"date": "Mar 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Mar 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Mar 25, 2024 Monday", "holiday": "Holi"},
        {"date": "Mar 29, 2024 Friday", "holiday": "Good Friday"},
        {"date": "Apr 10, 2024 Wednesday", "holiday": "Idul Fitr"},
        {"date": "Apr 11, 2024 Thursday", "holiday": "Idul Fitr"},
        {"date": "Apr 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Apr 17, 2024 Wednesday", "holiday": "Ram Navami"},
        {"date": "Apr 21, 2024 Sunday", "holiday": "Mahavir Jayanti"},
        {"date": "Apr 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "May 11, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "May 23, 2024 Thursday", "holiday": "Buddha Purnima"},
        {"date": "May 25, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jun 8, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jun 17, 2024 Monday", "holiday": "Bakrid / Eid al Adha"},
        {"date": "Jun 22, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jul 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jul 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Aug 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Aug 15, 2024 Thursday", "holiday": "Independence Day"},
        {"date": "Aug 24, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Aug 26, 2024 Monday", "holiday": "Janmashtami"},
        {"date": "Sep 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Sep 16, 2024 Monday", "holiday": "Eid e Milad"},
        {"date": "Sep 28, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Oct 2, 2024 Wednesday", "holiday": "Gandhi Jayanti"},
        {"date": "Oct 12, 2024 Saturday", "holiday": "Vijaya Dashami"},
        {
          "date": "Oct 17, 2024 Thursday",
          "holiday": "Maharishi Valmiki Jayanti"
        },
        {"date": "Oct 26, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Oct 31, 2024 Thursday", "holiday": "Diwali"},
        {"date": "Nov 1, 2024 Friday", "holiday": "Diwali"},
        {"date": "Nov 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Nov 15, 2024 Friday", "holiday": "Guru Nanak Jayanti"},
        {"date": "Nov 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Dec 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Dec 25, 2024 Wednesday", "holiday": "Christmas Day"},
        {"date": "Dec 28, 2024 Saturday", "holiday": "Fourth Saturday"}
      ]
    },
    {
      "poster": "assets/images/place/dadra.jpg",
      "title": "Dadra and Nagar Haveli",
      "list": [
        {"date": "Jan 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jan 14, 2024 Sunday", "holiday": "Makara Sankranti"},
        {"date": "Jan 26, 2024 Friday", "holiday": "Republic Day"},
        {"date": "Jan 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Feb 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Feb 24, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Mar 8, 2024 Friday", "holiday": "Maha Shivaratri"},
        {"date": "Mar 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Mar 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Mar 25, 2024 Monday", "holiday": "Holi"},
        {"date": "Mar 29, 2024 Friday", "holiday": "Good Friday"},
        {"date": "Apr 9, 2024 Tuesday", "holiday": "Ugadi"},
        {"date": "Apr 10, 2024 Wednesday", "holiday": "Idul Fitr"},
        {"date": "Apr 11, 2024 Thursday", "holiday": "Idul Fitr"},
        {"date": "Apr 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Apr 17, 2024 Wednesday", "holiday": "Ram Navami"},
        {"date": "Apr 21, 2024 Sunday", "holiday": "Mahavir Jayanti"},
        {"date": "Apr 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "May 11, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "May 25, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jun 8, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jun 22, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jul 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jul 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Aug 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Aug 15, 2024 Thursday", "holiday": "Parsi New Year"},
        {"date": "Aug 19, 2024 Monday", "holiday": "Raksha Bandhan"},
        {"date": "Aug 24, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Aug 26, 2024 Monday", "holiday": "Janmashtami"},
        {"date": "Sep 7, 2024 Saturday", "holiday": "Ganesh Chaturthi"},
        {"date": "Sep 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Sep 16, 2024 Monday", "holiday": "Eid e Milad"},
        {"date": "Sep 28, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Oct 2, 2024 Wednesday", "holiday": "Gandhi Jayanti"},
        {"date": "Oct 11, 2024 Friday", "holiday": "Maha Ashtami"},
        {"date": "Oct 12, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Oct 26, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Oct 31, 2024 Thursday", "holiday": "Diwali"},
        {"date": "Nov 1, 2024 Friday", "holiday": "Diwali"},
        {"date": "Nov 7, 2024 Thursday", "holiday": "Chhath Puja"},
        {"date": "Nov 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Nov 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Dec 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Dec 25, 2024 Wednesday", "holiday": "Christmas Day"},
        {"date": "Dec 28, 2024 Saturday", "holiday": "Fourth Saturday"}
      ]
    },
    {
      "poster": "assets/images/place/diu.jpg",
      "title": "Daman and Diu",
      "list": [
        {"date": "Jan 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jan 14, 2024 Sunday", "holiday": "Makara Sankranti"},
        {"date": "Jan 26, 2024 Friday", "holiday": "Republic Day"},
        {"date": "Jan 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Feb 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Feb 24, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Mar 8, 2024 Friday", "holiday": "Maha Shivaratri"},
        {"date": "Mar 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Mar 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Mar 25, 2024 Monday", "holiday": "Holi"},
        {"date": "Mar 29, 2024 Friday", "holiday": "Good Friday"},
        {"date": "Apr 9, 2024 Tuesday", "holiday": "Ugadi"},
        {"date": "Apr 10, 2024 Wednesday", "holiday": "Idul Fitr"},
        {"date": "Apr 11, 2024 Thursday", "holiday": "Idul Fitr"},
        {"date": "Apr 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Apr 17, 2024 Wednesday", "holiday": "Ram Navami"},
        {"date": "Apr 21, 2024 Sunday", "holiday": "Mahavir Jayanti"},
        {"date": "Apr 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "May 11, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "May 25, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jun 8, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jun 22, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jul 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jul 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Aug 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Aug 15, 2024 Thursday", "holiday": "Parsi New Year"},
        {"date": "Aug 19, 2024 Monday", "holiday": "Raksha Bandhan"},
        {"date": "Aug 24, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Aug 26, 2024 Monday", "holiday": "Janmashtami"},
        {"date": "Sep 7, 2024 Saturday", "holiday": "Ganesh Chaturthi"},
        {"date": "Sep 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Sep 16, 2024 Monday", "holiday": "Eid e Milad"},
        {"date": "Sep 28, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Oct 2, 2024 Wednesday", "holiday": "Gandhi Jayanti"},
        {"date": "Oct 11, 2024 Friday", "holiday": "Maha Ashtami"},
        {"date": "Oct 12, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Oct 13, 2024 Sunday", "holiday": "Vijaya Dashami"},
        {"date": "Oct 26, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Oct 31, 2024 Thursday", "holiday": "Diwali"},
        {"date": "Nov 1, 2024 Friday", "holiday": "Diwali"},
        {"date": "Nov 2, 2024 Saturday", "holiday": "Deepavali Holiday"},
        {"date": "Nov 7, 2024 Thursday", "holiday": "Chhath Puja"},
        {"date": "Nov 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Nov 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Dec 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Dec 19, 2024 Thursday", "holiday": "Liberation Day"},
        {"date": "Dec 25, 2024 Wednesday", "holiday": "Christmas Day"},
        {"date": "Dec 28, 2024 Saturday", "holiday": "Fourth Saturday"}
      ]
    },
    {
      "poster": "assets/images/place/gujrat.jpg",
      "title": "Gujarat",
      "list": [
        {"date": "Jan 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jan 14, 2024 Sunday", "holiday": "Makara Sankranti"},
        {"date": "Jan 15, 2024 Monday", "holiday": "Makara Sankranti"},
        {"date": "Jan 26, 2024 Friday", "holiday": "Republic Day"},
        {"date": "Jan 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Feb 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Feb 24, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Mar 8, 2024 Friday", "holiday": "Maha Shivaratri"},
        {"date": "Mar 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Mar 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Mar 25, 2024 Monday", "holiday": "Holi"},
        {"date": "Mar 29, 2024 Friday", "holiday": "Good Friday"},
        {"date": "Apr 9, 2024 Tuesday", "holiday": "Ugadi"},
        {"date": "Apr 10, 2024 Wednesday", "holiday": "Idul Fitr"},
        {"date": "Apr 11, 2024 Thursday", "holiday": "Idul Fitr"},
        {"date": "Apr 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Apr 14, 2024 Sunday", "holiday": "Dr Ambedkar Jayanti"},
        {"date": "Apr 17, 2024 Wednesday", "holiday": "Ram Navami"},
        {"date": "Apr 21, 2024 Sunday", "holiday": "Mahavir Jayanti"},
        {"date": "Apr 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {
          "date": "May 10, 2024 Friday",
          "holiday": "Maharshi Parasuram Jayanti"
        },
        {"date": "May 11, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "May 25, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jun 8, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jun 17, 2024 Monday", "holiday": "Bakrid / Eid al Adha"},
        {"date": "Jun 22, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jul 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jul 17, 2024 Wednesday", "holiday": "Muharram"},
        {"date": "Jul 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Aug 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Aug 15, 2024 Thursday", "holiday": "Parsi New Year"},
        {"date": "Aug 19, 2024 Monday", "holiday": "Raksha Bandhan"},
        {"date": "Aug 24, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Aug 26, 2024 Monday", "holiday": "Janmashtami"},
        {"date": "Sep 7, 2024 Saturday", "holiday": "Ganesh Chaturthi"},
        {"date": "Sep 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Sep 16, 2024 Monday", "holiday": "Eid e Milad"},
        {"date": "Sep 28, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Oct 2, 2024 Wednesday", "holiday": "Gandhi Jayanti"},
        {"date": "Oct 12, 2024 Saturday", "holiday": "Vijaya Dashami"},
        {"date": "Oct 13, 2024 Sunday", "holiday": "Vijaya Dashami"},
        {"date": "Oct 26, 2024 Saturday", "holiday": "Fourth Saturday"},
        {
          "date": "Oct 31, 2024 Thursday",
          "holiday": "Sardar Vallabhbhai Patel Jayanti"
        },
        {"date": "Nov 1, 2024 Friday", "holiday": "Diwali"},
        {"date": "Nov 2, 2024 Saturday", "holiday": "Vikram Samvat New Year"},
        {"date": "Nov 3, 2024 Sunday", "holiday": "Bhai Dooj"},
        {"date": "Nov 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Nov 15, 2024 Friday", "holiday": "Guru Nanak Jayanti"},
        {"date": "Nov 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Dec 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Dec 25, 2024 Wednesday", "holiday": "Christmas Day"},
        {"date": "Dec 28, 2024 Saturday", "holiday": "Fourth Saturday"}
      ]
    },
    {
      "poster": "assets/images/place/goa.jpg",
      "title": "Goa",
      "list": [
        {"date": "Jan 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jan 26, 2024 Friday", "holiday": "Republic Day"},
        {"date": "Jan 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Feb 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Feb 24, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Mar 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Mar 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Mar 25, 2024 Monday", "holiday": "Holi"},
        {"date": "Mar 29, 2024 Friday", "holiday": "Good Friday"},
        {"date": "Apr 9, 2024 Tuesday", "holiday": "Ugadi"},
        {"date": "Apr 10, 2024 Wednesday", "holiday": "Idul Fitr"},
        {"date": "Apr 11, 2024 Thursday", "holiday": "Idul Fitr"},
        {"date": "Apr 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Apr 14, 2024 Sunday", "holiday": "Dr Ambedkar Jayanti"},
        {"date": "Apr 17, 2024 Wednesday", "holiday": "Ram Navami"},
        {"date": "Apr 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "May 1, 2024 Wednesday", "holiday": "May Day"},
        {"date": "May 11, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "May 25, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jun 8, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jun 17, 2024 Monday", "holiday": "Bakrid / Eid al Adha"},
        {"date": "Jun 22, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jul 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jul 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Aug 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Aug 15, 2024 Thursday", "holiday": "Independence Day"},
        {"date": "Aug 24, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Sep 7, 2024 Saturday", "holiday": "Ganesh Chaturthi"},
        {"date": "Sep 8, 2024 Sunday", "holiday": "Ganesh Chaturthi Holiday"},
        {"date": "Sep 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Sep 28, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Oct 2, 2024 Wednesday", "holiday": "Gandhi Jayanti"},
        {"date": "Oct 12, 2024 Saturday", "holiday": "Vijaya Dashami"},
        {"date": "Oct 13, 2024 Sunday", "holiday": "Vijaya Dashami"},
        {"date": "Oct 26, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Oct 31, 2024 Thursday", "holiday": "Deepavali"},
        {"date": "Nov 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Nov 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {
          "date": "Dec 3, 2024 Tuesday",
          "holiday": "Feast of St Francis Xavier"
        },
        {"date": "Dec 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Dec 19, 2024 Thursday", "holiday": "Liberation Day"},
        {"date": "Dec 25, 2024 Wednesday", "holiday": "Christmas Day"},
        {"date": "Dec 28, 2024 Saturday", "holiday": "Fourth Saturday"}
      ]
    },
    {
      "poster": "assets/images/place/himachal.jpg",
      "title": "Himachal Pradesh",
      "list": [
        {"date": "Jan 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jan 25, 2024 Thursday", "holiday": "State Day"},
        {"date": "Jan 26, 2024 Friday", "holiday": "Republic Day"},
        {"date": "Jan 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Feb 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Feb 24, 2024 Saturday", "holiday": "Guru Ravidas Jayanti"},
        {"date": "Mar 8, 2024 Friday", "holiday": "Maha Shivaratri"},
        {"date": "Mar 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Mar 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Mar 25, 2024 Monday", "holiday": "Holi"},
        {"date": "Mar 29, 2024 Friday", "holiday": "Good Friday"},
        {"date": "Apr 10, 2024 Wednesday", "holiday": "Idul Fitr"},
        {"date": "Apr 11, 2024 Thursday", "holiday": "Idul Fitr"},
        {"date": "Apr 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Apr 14, 2024 Sunday", "holiday": "Dr Ambedkar Jayanti"},
        {"date": "Apr 15, 2024 Monday", "holiday": "Himachal Day"},
        {"date": "Apr 17, 2024 Wednesday", "holiday": "Ram Navami"},
        {"date": "Apr 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {
          "date": "May 10, 2024 Friday",
          "holiday": "Maharshi Parasuram Jayanti"
        },
        {"date": "May 11, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "May 23, 2024 Thursday", "holiday": "Buddha Purnima"},
        {"date": "May 25, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jun 8, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jun 9, 2024 Sunday", "holiday": "Maharana Pratap Jayanti"},
        {"date": "Jun 17, 2024 Monday", "holiday": "Bakrid / Eid al Adha"},
        {"date": "Jun 22, 2024 Saturday", "holiday": "Sant Guru Kabir Jayanti"},
        {"date": "Jul 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jul 17, 2024 Wednesday", "holiday": "Muharram"},
        {"date": "Jul 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Aug 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Aug 15, 2024 Thursday", "holiday": "Independence Day"},
        {"date": "Aug 24, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Aug 26, 2024 Monday", "holiday": "Janmashtami"},
        {"date": "Sep 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Sep 28, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Oct 2, 2024 Wednesday", "holiday": "Gandhi Jayanti"},
        {"date": "Oct 12, 2024 Saturday", "holiday": "Vijaya Dashami"},
        {"date": "Oct 13, 2024 Sunday", "holiday": "Vijaya Dashami"},
        {
          "date": "Oct 17, 2024 Thursday",
          "holiday": "Maharishi Valmiki Jayanti"
        },
        {"date": "Oct 26, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Oct 31, 2024 Thursday", "holiday": "Diwali"},
        {"date": "Nov 1, 2024 Friday", "holiday": "Diwali"},
        {"date": "Nov 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Nov 15, 2024 Friday", "holiday": "Guru Nanak Jayanti"},
        {"date": "Nov 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Dec 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Dec 25, 2024 Wednesday", "holiday": "Christmas Day"},
        {"date": "Dec 28, 2024 Saturday", "holiday": "Fourth Saturday"}
      ]
    },
    {
      "poster": "assets/images/place/jarkhand.jpg",
      "title": "Jharkhand",
      "list": [
        {"date": "Jan 13, 2024 Saturday", "holiday": "Second Saturday"},
        {
          "date": "Jan 23, 2024 Tuesday",
          "holiday": "Netaji Subhas Chandra Bose Jayanti"
        },
        {"date": "Jan 26, 2024 Friday", "holiday": "Republic Day"},
        {"date": "Jan 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Feb 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Feb 24, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Mar 8, 2024 Friday", "holiday": "Maha Shivaratri"},
        {"date": "Mar 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Mar 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Mar 25, 2024 Monday", "holiday": "Holi"},
        {"date": "Mar 29, 2024 Friday", "holiday": "Good Friday"},
        {"date": "Apr 10, 2024 Wednesday", "holiday": "Idul Fitr"},
        {"date": "Apr 11, 2024 Thursday", "holiday": "Sarhul"},
        {"date": "Apr 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Apr 14, 2024 Sunday", "holiday": "Dr Ambedkar Jayanti"},
        {"date": "Apr 17, 2024 Wednesday", "holiday": "Ram Navami"},
        {"date": "Apr 21, 2024 Sunday", "holiday": "Mahavir Jayanti"},
        {"date": "Apr 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "May 11, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "May 23, 2024 Thursday", "holiday": "Buddha Purnima"},
        {"date": "May 25, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jun 8, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jun 17, 2024 Monday", "holiday": "Bakrid / Eid al Adha"},
        {"date": "Jun 22, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jul 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jul 17, 2024 Wednesday", "holiday": "Muharram"},
        {"date": "Jul 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Aug 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Aug 15, 2024 Thursday", "holiday": "Independence Day"},
        {"date": "Aug 24, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Aug 26, 2024 Monday", "holiday": "Janmashtami"},
        {"date": "Sep 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Sep 16, 2024 Monday", "holiday": "Eid e Milad"},
        {"date": "Sep 28, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Oct 2, 2024 Wednesday", "holiday": "Gandhi Jayanti"},
        {"date": "Oct 11, 2024 Friday", "holiday": "Maha Ashtami"},
        {"date": "Oct 12, 2024 Saturday", "holiday": "Maha Navami"},
        {"date": "Oct 13, 2024 Sunday", "holiday": "Vijaya Dashami"},
        {"date": "Oct 26, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Oct 31, 2024 Thursday", "holiday": "Diwali"},
        {"date": "Nov 1, 2024 Friday", "holiday": "Diwali"},
        {"date": "Nov 7, 2024 Thursday", "holiday": "Chhath Puja"},
        {"date": "Nov 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Nov 15, 2024 Friday", "holiday": "Guru Nanak Jayanti"},
        {"date": "Nov 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Dec 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Dec 25, 2024 Wednesday", "holiday": "Christmas Day"},
        {"date": "Dec 28, 2024 Saturday", "holiday": "Fourth Saturday"}
      ]
    },
    {
      "poster": "assets/images/place/karnatak.jpg",
      "title": "Karnataka",
      "list": [
        {"date": "Jan 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jan 15, 2024 Monday", "holiday": "Makara Sankranti"},
        {"date": "Jan 26, 2024 Friday", "holiday": "Republic Day"},
        {"date": "Jan 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Feb 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Feb 24, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Mar 8, 2024 Friday", "holiday": "Maha Shivaratri"},
        {"date": "Mar 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Mar 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Mar 29, 2024 Friday", "holiday": "Good Friday"},
        {"date": "Apr 9, 2024 Tuesday", "holiday": "Ugadi"},
        {"date": "Apr 10, 2024 Wednesday", "holiday": "Idul Fitr"},
        {"date": "Apr 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Apr 14, 2024 Sunday", "holiday": "Dr Ambedkar Jayanti"},
        {"date": "Apr 21, 2024 Sunday", "holiday": "Mahavir Jayanti"},
        {"date": "Apr 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "May 1, 2024 Wednesday", "holiday": "May Day"},
        {"date": "May 10, 2024 Friday", "holiday": "Basava Jayanti"},
        {"date": "May 11, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "May 25, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jun 8, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jun 17, 2024 Monday", "holiday": "Bakrid / Eid al Adha"},
        {"date": "Jun 22, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jul 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jul 17, 2024 Wednesday", "holiday": "Muharram"},
        {"date": "Jul 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Aug 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Aug 15, 2024 Thursday", "holiday": "Independence Day"},
        {"date": "Aug 24, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Sep 7, 2024 Saturday", "holiday": "Ganesh Chaturthi"},
        {"date": "Sep 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Sep 16, 2024 Monday", "holiday": "Eid e Milad"},
        {"date": "Sep 28, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Oct 2, 2024 Wednesday", "holiday": "Gandhi Jayanti"},
        {"date": "Oct 12, 2024 Saturday", "holiday": "Maha Navami"},
        {"date": "Oct 13, 2024 Sunday", "holiday": "Vijaya Dashami"},
        {
          "date": "Oct 17, 2024 Thursday",
          "holiday": "Maharishi Valmiki Jayanti"
        },
        {"date": "Oct 26, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Oct 31, 2024 Thursday", "holiday": "Deepavali"},
        {"date": "Nov 1, 2024 Friday", "holiday": "Kannada Rajyothsava"},
        {"date": "Nov 2, 2024 Saturday", "holiday": "Deepavali Holiday"},
        {"date": "Nov 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Nov 18, 2024 Monday", "holiday": "Kanakadasa Jayanti"},
        {"date": "Nov 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Dec 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Dec 25, 2024 Wednesday", "holiday": "Christmas Day"},
        {"date": "Dec 28, 2024 Saturday", "holiday": "Fourth Saturday"}
      ]
    },
    {
      "poster": "assets/images/place/maharastra.jpg",
      "title": "Maharashtra",
      "list": [
        {"date": "Jan 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jan 26, 2024 Friday", "holiday": "Republic Day"},
        {"date": "Jan 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Feb 10, 2024 Saturday", "holiday": "Second Saturday"},
        {
          "date": "Feb 19, 2024 Monday",
          "holiday": "Chhatrapati Shivaji Maharaj Jayanti"
        },
        {"date": "Feb 24, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Mar 8, 2024 Friday", "holiday": "Maha Shivaratri"},
        {"date": "Mar 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Mar 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Mar 25, 2024 Monday", "holiday": "Holi"},
        {"date": "Mar 29, 2024 Friday", "holiday": "Good Friday"},
        {"date": "Apr 9, 2024 Tuesday", "holiday": "Gudi Padwa"},
        {"date": "Apr 10, 2024 Wednesday", "holiday": "Idul Fitr"},
        {"date": "Apr 11, 2024 Thursday", "holiday": "Idul Fitr"},
        {"date": "Apr 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Apr 14, 2024 Sunday", "holiday": "Dr Ambedkar Jayanti"},
        {"date": "Apr 17, 2024 Wednesday", "holiday": "Ram Navami"},
        {"date": "Apr 21, 2024 Sunday", "holiday": "Mahavir Jayanti"},
        {"date": "Apr 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "May 1, 2024 Wednesday", "holiday": "Maharashtra Day"},
        {"date": "May 11, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "May 23, 2024 Thursday", "holiday": "Buddha Purnima"},
        {"date": "May 25, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jun 8, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jun 17, 2024 Monday", "holiday": "Bakrid / Eid al Adha"},
        {"date": "Jun 22, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jul 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jul 17, 2024 Wednesday", "holiday": "Muharram"},
        {"date": "Jul 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Aug 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Aug 15, 2024 Thursday", "holiday": "Parsi New Year"},
        {"date": "Aug 24, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Sep 7, 2024 Saturday", "holiday": "Ganesh Chaturthi"},
        {"date": "Sep 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Sep 16, 2024 Monday", "holiday": "Eid e Milad"},
        {"date": "Sep 28, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Oct 2, 2024 Wednesday", "holiday": "Gandhi Jayanti"},
        {"date": "Oct 12, 2024 Saturday", "holiday": "Vijaya Dashami"},
        {"date": "Oct 13, 2024 Sunday", "holiday": "Vijaya Dashami"},
        {"date": "Oct 26, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Nov 1, 2024 Friday", "holiday": "Diwali"},
        {"date": "Nov 2, 2024 Saturday", "holiday": "Deepavali Holiday"},
        {"date": "Nov 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Nov 15, 2024 Friday", "holiday": "Guru Nanak Jayanti"},
        {"date": "Nov 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Dec 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Dec 25, 2024 Wednesday", "holiday": "Christmas Day"},
        {"date": "Dec 28, 2024 Saturday", "holiday": "Fourth Saturday"}
      ]
    },
    {
      "poster": "assets/images/place/nagaland.jpg",
      "title": "Nagaland",
      "list": [
        {"date": "Jan 1, 2024 Monday", "holiday": "New Year's Day"},
        {"date": "Jan 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jan 26, 2024 Friday", "holiday": "Republic Day"},
        {"date": "Jan 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Feb 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Feb 24, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Mar 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Mar 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Mar 25, 2024 Monday", "holiday": "Holi"},
        {"date": "Mar 29, 2024 Friday", "holiday": "Good Friday"},
        {"date": "Mar 30, 2024 Saturday", "holiday": "Easter Saturday"},
        {"date": "Mar 31, 2024 Sunday", "holiday": "Easter Sunday"},
        {"date": "Apr 10, 2024 Wednesday", "holiday": "Idul Fitr"},
        {"date": "Apr 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Apr 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "May 11, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "May 25, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jun 8, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jun 17, 2024 Monday", "holiday": "Bakrid / Eid al Adha"},
        {"date": "Jun 22, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jul 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jul 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Aug 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Aug 15, 2024 Thursday", "holiday": "Independence Day"},
        {"date": "Aug 24, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Aug 26, 2024 Monday", "holiday": "Janmashtami"},
        {"date": "Sep 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Sep 16, 2024 Monday", "holiday": "Eid e Milad"},
        {"date": "Sep 28, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Oct 2, 2024 Wednesday", "holiday": "Gandhi Jayanti"},
        {"date": "Oct 12, 2024 Saturday", "holiday": "Maha Navami"},
        {"date": "Oct 13, 2024 Sunday", "holiday": "Vijaya Dashami"},
        {"date": "Oct 26, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Nov 1, 2024 Friday", "holiday": "Diwali"},
        {"date": "Nov 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Nov 15, 2024 Friday", "holiday": "Guru Nanak Jayanti"},
        {"date": "Nov 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Dec 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Dec 25, 2024 Wednesday", "holiday": "Christmas Day"},
        {"date": "Dec 28, 2024 Saturday", "holiday": "Fourth Saturday"}
      ]
    },
    {
      "poster": "assets/images/place/delhi.jpg",
      "title": "New Delhi",
      "list": [
        {"date": "Jan 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jan 26, 2024 Friday", "holiday": "Republic Day"},
        {"date": "Jan 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Feb 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Feb 24, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Mar 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Mar 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Mar 25, 2024 Monday", "holiday": "Holi"},
        {"date": "Mar 29, 2024 Friday", "holiday": "Good Friday"},
        {"date": "Apr 10, 2024 Wednesday", "holiday": "Idul Fitr"},
        {"date": "Apr 11, 2024 Thursday", "holiday": "Idul Fitr"},
        {"date": "Apr 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Apr 17, 2024 Wednesday", "holiday": "Ram Navami"},
        {"date": "Apr 21, 2024 Sunday", "holiday": "Mahavir Jayanti"},
        {"date": "Apr 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "May 11, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "May 23, 2024 Thursday", "holiday": "Buddha Purnima"},
        {"date": "May 25, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jun 8, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jun 17, 2024 Monday", "holiday": "Bakrid / Eid al Adha"},
        {"date": "Jun 22, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jul 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jul 17, 2024 Wednesday", "holiday": "Muharram"},
        {"date": "Jul 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Aug 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Aug 15, 2024 Thursday", "holiday": "Independence Day"},
        {"date": "Aug 24, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Aug 26, 2024 Monday", "holiday": "Janmashtami"},
        {"date": "Sep 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Sep 16, 2024 Monday", "holiday": "Eid e Milad"},
        {"date": "Sep 28, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Oct 2, 2024 Wednesday", "holiday": "Gandhi Jayanti"},
        {"date": "Oct 12, 2024 Saturday", "holiday": "Vijaya Dashami"},
        {"date": "Oct 13, 2024 Sunday", "holiday": "Vijaya Dashami"},
        {"date": "Oct 26, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Oct 31, 2024 Thursday", "holiday": "Diwali"},
        {"date": "Nov 1, 2024 Friday", "holiday": "Diwali"},
        {"date": "Nov 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Nov 15, 2024 Friday", "holiday": "Guru Nanak Jayanti"},
        {"date": "Nov 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Dec 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Dec 25, 2024 Wednesday", "holiday": "Christmas Day"},
        {"date": "Dec 28, 2024 Saturday", "holiday": "Fourth Saturday"}
      ]
    },
    {
      "poster": "assets/images/place/punducher.jpeg",
      "title": "Pondicherry",
      "list": [
        {"date": "Jan 1, 2024 Monday", "holiday": "New Year's Day"},
        {"date": "Jan 13, 2024 Saturday", "holiday": "Second Saturday "},
        {"date": "Jan 15, 2024 Monday", "holiday": "Pongal"},
        {"date": "Jan 16, 2024 Tuesday", "holiday": "Thiruvalluvar Day"},
        {"date": "Jan 17, 2024 Wednesday", "holiday": "Uzhavar Thirunal"},
        {"date": "Jan 26, 2024 Friday", "holiday": "Republic Day"},
        {"date": "Jan 27, 2024 Saturday", "holiday": "Fourth Saturday "},
        {"date": "Feb 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Feb 24, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Mar 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Mar 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Mar 29, 2024 Friday", "holiday": "Good Friday"},
        {"date": "Apr 10, 2024 Wednesday", "holiday": "Idul Fitr"},
        {"date": "Apr 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Apr 14, 2024 Sunday", "holiday": "Dr Ambedkar Jayanti"},
        {"date": "Apr 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "May 1, 2024 Wednesday", "holiday": "May Day"},
        {"date": "May 11, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "May 25, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jun 8, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jun 17, 2024 Monday", "holiday": "Bakrid / Eid al Adha"},
        {"date": "Jun 22, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jul 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jul 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Aug 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Aug 15, 2024 Thursday", "holiday": "Independence Day"},
        {"date": "Aug 16, 2024 Friday", "holiday": "De Jure Transfer Day"},
        {"date": "Aug 24, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Sep 7, 2024 Saturday", "holiday": "Ganesh Chaturthi"},
        {"date": "Sep 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Sep 16, 2024 Monday", "holiday": "Eid e Milad"},
        {"date": "Sep 28, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Oct 2, 2024 Wednesday", "holiday": "Gandhi Jayanti"},
        {"date": "Oct 11, 2024 Friday", "holiday": "Maha Navami"},
        {"date": "Oct 12, 2024 Saturday", "holiday": "Maha Navami"},
        {"date": "Oct 26, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Oct 31, 2024 Thursday", "holiday": "Deepavali"},
        {"date": "Nov 1, 2024 Friday", "holiday": "Puducherry Liberation Day"},
        {"date": "Nov 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Nov 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Dec 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Dec 25, 2024 Wednesday", "holiday": "Christmas Day"},
        {"date": "Dec 28, 2024 Saturday", "holiday": "Fourth Saturday"}
      ]
    },
    {
      "poster": "assets/images/place/panjab.jpg",
      "title": "Punjab",
      "list": [
        {"date": "Jan 13, 2024 Saturday", "holiday": "Second Saturday"},
        {
          "date": "Jan 17, 2024 Wednesday",
          "holiday": "Guru Gobind Singh Jayanti"
        },
        {"date": "Jan 26, 2024 Friday", "holiday": "Republic Day"},
        {"date": "Jan 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Feb 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Feb 24, 2024 Saturday", "holiday": "Guru Ravidas Jayanti"},
        {"date": "Mar 8, 2024 Friday", "holiday": "Maha Shivaratri"},
        {"date": "Mar 9, 2024 Saturday", "holiday": "Second Saturday"},
        {
          "date": "Mar 23, 2024 Saturday",
          "holiday": "S. Bhagat Singh's Martyrdom Day"
        },
        {"date": "Mar 25, 2024 Monday", "holiday": "Holi"},
        {"date": "Mar 29, 2024 Friday", "holiday": "Good Friday"},
        {
          "date": "Apr 8, 2024 Monday",
          "holiday": "Parkash Gurpurab of Sri Guru Ram Dass Ji"
        },
        {"date": "Apr 10, 2024 Wednesday", "holiday": "Idul Fitr"},
        {"date": "Apr 11, 2024 Thursday", "holiday": "Idul Fitr"},
        {"date": "Apr 13, 2024 Saturday", "holiday": "Vaisakh"},
        {"date": "Apr 14, 2024 Sunday", "holiday": "Dr Ambedkar Jayanti"},
        {"date": "Apr 17, 2024 Wednesday", "holiday": "Ram Navami"},
        {"date": "Apr 21, 2024 Sunday", "holiday": "Mahavir Jayanti"},
        {"date": "Apr 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "May 1, 2024 Wednesday", "holiday": "May Day"},
        {
          "date": "May 10, 2024 Friday",
          "holiday": "Maharshi Parasuram Jayanti"
        },
        {"date": "May 11, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "May 25, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jun 8, 2024 Saturday", "holiday": "Second Saturday"},
        {
          "date": "Jun 10, 2024 Monday",
          "holiday": "Sri Guru Arjun Dev Ji's Martyrdom Day"
        },
        {"date": "Jun 17, 2024 Monday", "holiday": "Bakrid / Eid al Adha"},
        {"date": "Jun 22, 2024 Saturday", "holiday": "Sant Guru Kabir Jayanti"},
        {"date": "Jul 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jul 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Aug 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Aug 15, 2024 Thursday", "holiday": "Independence Day"},
        {"date": "Aug 26, 2024 Monday", "holiday": "Janmashtami"},
        {"date": "Sep 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Sep 28, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Oct 2, 2024 Wednesday", "holiday": "Gandhi Jayanti"},
        {"date": "Oct 3, 2024 Thursday", "holiday": "Maharaja Agrasen Jayanti"},
        {"date": "Oct 12, 2024 Saturday", "holiday": "Vijaya Dashami"},
        {"date": "Oct 13, 2024 Sunday", "holiday": "Vijaya Dashami"},
        {
          "date": "Oct 17, 2024 Thursday",
          "holiday": "Maharishi Valmiki Jayanti"
        },
        {"date": "Oct 26, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Oct 31, 2024 Thursday", "holiday": "Diwali"},
        {"date": "Nov 1, 2024 Friday", "holiday": "Diwali"},
        {"date": "Nov 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Nov 15, 2024 Friday", "holiday": "Guru Nanak Jayanti"},
        {
          "date": "Nov 16, 2024 Saturday",
          "holiday": "Shahidi Diwas S. Kartar Singh Sarabha Ji"
        },
        {"date": "Nov 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {
          "date": "Dec 6, 2024 Friday",
          "holiday": "Sri Guru Teg Bahadur Ji's Martyrdom Day"
        },
        {"date": "Dec 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Dec 25, 2024 Wednesday", "holiday": "Christmas Day"},
        {"date": "Dec 27, 2024 Friday", "holiday": "Shaheedi Sabha"},
        {"date": "Dec 28, 2024 Saturday", "holiday": "Fourth Saturday"}
      ]
    },
    {
      "poster": "assets/images/place/rajasthan.jpg",
      "title": "Rajasthan",
      "list": [
        {"date": "Jan 1, 2024 Monday", "holiday": "New Year's Day"},
        {"date": "Jan 13, 2024 Saturday", "holiday": "Second Saturday"},
        {
          "date": "Jan 17, 2024 Wednesday",
          "holiday": "Guru Gobind Singh Jayanti"
        },
        {"date": "Jan 26, 2024 Friday", "holiday": "Republic Day"},
        {"date": "Jan 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Feb 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Feb 24, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Mar 8, 2024 Friday", "holiday": "Maha Shivaratri"},
        {"date": "Mar 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Mar 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Mar 25, 2024 Monday", "holiday": "Holi"},
        {"date": "Mar 29, 2024 Friday", "holiday": "Good Friday"},
        {"date": "Apr 9, 2024 Tuesday", "holiday": "Ugadi"},
        {"date": "Apr 10, 2024 Wednesday", "holiday": "Idul Fitr"},
        {"date": "Apr 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Apr 14, 2024 Sunday", "holiday": "Dr Ambedkar Jayanti"},
        {"date": "Apr 17, 2024 Wednesday", "holiday": "Ram Navami"},
        {"date": "Apr 21, 2024 Sunday", "holiday": "Mahavir Jayanti"},
        {"date": "Apr 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {
          "date": "May 10, 2024 Friday",
          "holiday": "Maharshi Parasuram Jayanti"
        },
        {"date": "May 11, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "May 25, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jun 8, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jun 9, 2024 Sunday", "holiday": "Maharana Pratap Jayanti"},
        {"date": "Jun 17, 2024 Monday", "holiday": "Bakrid / Eid al Adha"},
        {"date": "Jun 22, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jul 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jul 17, 2024 Wednesday", "holiday": "Muharram"},
        {"date": "Jul 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Aug 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Aug 15, 2024 Thursday", "holiday": "Independence Day"},
        {"date": "Aug 19, 2024 Monday", "holiday": "Raksha Bandhan"},
        {"date": "Aug 24, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Aug 26, 2024 Monday", "holiday": "Janmashtami"},
        {"date": "Sep 13, 2024 Friday", "holiday": "Teja Dashmi"},
        {"date": "Sep 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Sep 16, 2024 Monday", "holiday": "Eid e Milad"},
        {"date": "Sep 28, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Oct 2, 2024 Wednesday", "holiday": "Gandhi Jayanti"},
        {"date": "Oct 3, 2024 Thursday", "holiday": "Ghatasthapana"},
        {"date": "Oct 11, 2024 Friday", "holiday": "Maha Ashtami"},
        {"date": "Oct 12, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Oct 13, 2024 Sunday", "holiday": "Vijaya Dashami"},
        {"date": "Oct 26, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Nov 1, 2024 Friday", "holiday": "Diwali"},
        {"date": "Nov 2, 2024 Saturday", "holiday": "Deepavali Holiday"},
        {"date": "Nov 3, 2024 Sunday", "holiday": "Bhai Dooj"},
        {"date": "Nov 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Nov 15, 2024 Friday", "holiday": "Guru Nanak Jayanti"},
        {"date": "Nov 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Dec 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Dec 25, 2024 Wednesday", "holiday": "Christmas Day"},
        {"date": "Dec 28, 2024 Saturday", "holiday": "Fourth Saturday"}
      ]
    },
    {
      "poster": "assets/images/place/tripur.jpeg",
      "title": "Tripura",
      "list": [
        {"date": "Jan 13, 2024 Saturday", "holiday": "Second Saturday"},
        {
          "date": "Jan 23, 2024 Tuesday",
          "holiday": "Netaji Subhas Chandra Bose Jayanti"
        },
        {"date": "Jan 26, 2024 Friday", "holiday": "Republic Day"},
        {"date": "Jan 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Feb 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Feb 14, 2024 Wednesday", "holiday": "Vasant Panchami"},
        {"date": "Feb 24, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Mar 8, 2024 Friday", "holiday": "Maha Shivaratri"},
        {"date": "Mar 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Mar 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Mar 25, 2024 Monday", "holiday": "Holi"},
        {"date": "Mar 29, 2024 Friday", "holiday": "Good Friday"},
        {"date": "Apr 10, 2024 Wednesday", "holiday": "Idul Fitr"},
        {"date": "Apr 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Apr 14, 2024 Sunday", "holiday": "Bengali New Year"},
        {"date": "Apr 21, 2024 Sunday", "holiday": "Garia Puja"},
        {"date": "Apr 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "May 1, 2024 Wednesday", "holiday": "May Day"},
        {
          "date": "May 8, 2024 Wednesday",
          "holiday": "Guru Rabindranath Jayanti"
        },
        {"date": "May 11, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "May 23, 2024 Thursday", "holiday": "Buddha Purnima"},
        {"date": "May 24, 2024 Friday", "holiday": "Kazi Nazrul Islam Jayanti"},
        {"date": "May 25, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jun 8, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jun 17, 2024 Monday", "holiday": "Bakrid / Eid al Adha"},
        {"date": "Jun 22, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jul 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jul 17, 2024 Wednesday", "holiday": "Muharram"},
        {"date": "Jul 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Aug 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Aug 15, 2024 Thursday", "holiday": "Independence Day"},
        {"date": "Aug 24, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Aug 26, 2024 Monday", "holiday": "Janmashtami"},
        {"date": "Sep 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Sep 16, 2024 Monday", "holiday": "Eid e Milad"},
        {"date": "Sep 28, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Oct 2, 2024 Wednesday", "holiday": "Gandhi Jayanti"},
        {"date": "Oct 10, 2024 Thursday", "holiday": "Maha Saptami"},
        {"date": "Oct 11, 2024 Friday", "holiday": "Maha Ashtami"},
        {"date": "Oct 12, 2024 Saturday", "holiday": "Maha Navami"},
        {"date": "Oct 13, 2024 Sunday", "holiday": "Vijaya Dashami"},
        {"date": "Oct 17, 2024 Thursday", "holiday": "Lakshmi Puja"},
        {"date": "Oct 26, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Nov 1, 2024 Friday", "holiday": "Diwali"},
        {"date": "Nov 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Nov 23, 2024 Saturday", "holiday": ""},
        {"date": "Dec 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Dec 25, 2024 Wednesday", "holiday": "Christmas Day"},
        {"date": "Dec 28, 2024 Saturday", "holiday": "Fourth Saturday"}
      ]
    },
    {
      "poster": "assets/images/place/utarPradesh.jpg",
      "title": "Uttar Pradesh",
      "list": [
        {"date": "Jan 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jan 25, 2024 Thursday", "holiday": "Hazrat Ali Jayanti"},
        {"date": "Jan 26, 2024 Friday", "holiday": "Republic Day"},
        {"date": "Jan 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Feb 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Feb 24, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Mar 8, 2024 Friday", "holiday": "Maha Shivaratri"},
        {"date": "Mar 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Mar 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Mar 25, 2024 Monday", "holiday": "Holi"},
        {"date": "Mar 29, 2024 Friday", "holiday": "Good Friday"},
        {"date": "Apr 10, 2024 Wednesday", "holiday": "Idul Fitr"},
        {"date": "Apr 11, 2024 Thursday", "holiday": "Idul Fitr"},
        {"date": "Apr 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Apr 14, 2024 Sunday", "holiday": "Dr Ambedkar Jayanti"},
        {"date": "Apr 17, 2024 Wednesday", "holiday": "Ram Navami"},
        {"date": "Apr 21, 2024 Sunday", "holiday": "Mahavir Jayanti"},
        {"date": "Apr 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "May 11, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "May 23, 2024 Thursday", "holiday": "Buddha Purnima"},
        {"date": "May 25, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jun 8, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jun 17, 2024 Monday", "holiday": "Bakrid / Eid al Adha"},
        {"date": "Jun 22, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jul 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jul 17, 2024 Wednesday", "holiday": "Muharram"},
        {"date": "Jul 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Aug 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Aug 15, 2024 Thursday", "holiday": "Independence Day"},
        {"date": "Aug 19, 2024 Monday", "holiday": "Raksha Bandhan"},
        {"date": "Aug 24, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Aug 26, 2024 Monday", "holiday": "Janmashtami"},
        {"date": "Sep 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Sep 16, 2024 Monday", "holiday": "Eid e Milad"},
        {"date": "Sep 28, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Oct 2, 2024 Wednesday", "holiday": "Gandhi Jayanti"},
        {"date": "Oct 12, 2024 Saturday", "holiday": "Vijaya Dashami"},
        {"date": "Oct 13, 2024 Sunday", "holiday": "Vijaya Dashami"},
        {"date": "Oct 26, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Oct 31, 2024 Thursday", "holiday": "Diwali"},
        {"date": "Nov 1, 2024 Friday", "holiday": "Diwali"},
        {"date": "Nov 2, 2024 Saturday", "holiday": "Govardhan Puja"},
        {"date": "Nov 3, 2024 Sunday", "holiday": "Bhai Dooj"},
        {"date": "Nov 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Nov 15, 2024 Friday", "holiday": "Guru Nanak Jayanti"},
        {"date": "Nov 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Dec 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Dec 25, 2024 Wednesday", "holiday": "Christmas Day"},
        {"date": "Dec 28, 2024 Saturday", "holiday": "Fourth Saturday"}
      ]
    },
    {
      "poster": "assets/images/place/uttarakhand.jpg",
      "title": "Uttarakhand",
      "list": [
        {"date": "Jan 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jan 26, 2024 Friday", "holiday": "Republic Day"},
        {"date": "Jan 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Feb 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Feb 24, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Mar 8, 2024 Friday", "holiday": "Maha Shivaratri"},
        {"date": "Mar 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Mar 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Mar 25, 2024 Monday", "holiday": "Holi"},
        {"date": "Mar 29, 2024 Friday", "holiday": "Good Friday"},
        {"date": "Apr 10, 2024 Wednesday", "holiday": "Idul Fitr"},
        {"date": "Apr 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Apr 14, 2024 Sunday", "holiday": "Dr Ambedkar Jayanti"},
        {"date": "Apr 17, 2024 Wednesday", "holiday": "Ram Navami"},
        {"date": "Apr 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "May 11, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "May 23, 2024 Thursday", "holiday": "Buddha Purnima"},
        {"date": "May 25, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jun 8, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jun 17, 2024 Monday", "holiday": "Bakrid / Eid al Adha"},
        {"date": "Jun 22, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jul 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jul 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Aug 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Aug 15, 2024 Thursday", "holiday": "Independence Day"},
        {"date": "Aug 19, 2024 Monday", "holiday": "Raksha Bandhan"},
        {"date": "Aug 24, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Aug 26, 2024 Monday", "holiday": "Janmashtami"},
        {"date": "Sep 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Sep 16, 2024 Monday", "holiday": "Eid e Milad"},
        {"date": "Sep 28, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Oct 2, 2024 Wednesday", "holiday": "Gandhi Jayanti"},
        {"date": "Oct 12, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Oct 13, 2024 Sunday", "holiday": "Vijaya Dashami"},
        {"date": "Oct 26, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Nov 1, 2024 Friday", "holiday": "Diwali"},
        {"date": "Nov 2, 2024 Saturday", "holiday": "Deepavali Holiday"},
        {"date": "Nov 3, 2024 Sunday", "holiday": "Bhai Dooj"},
        {"date": "Nov 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Nov 15, 2024 Friday", "holiday": "Guru Nanak Jayanti"},
        {"date": "Nov 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Dec 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Dec 25, 2024 Wednesday", "holiday": "Christmas Day"},
        {"date": "Dec 28, 2024 Saturday", "holiday": "Fourth Saturday"}
      ]
    },
    {
      "poster": "assets/images/place/bengal.jpg",
      "title": "West Bengal",
      "list": [
        {"date": "Jan 12, 2024 Friday", "holiday": "Swami Vivekananda Jayanti"},
        {"date": "Jan 13, 2024 Saturday", "holiday": "Second Saturday"},
        {
          "date": "Jan 23, 2024 Tuesday",
          "holiday": "Netaji Subhas Chandra Bose Jayanti"
        },
        {"date": "Jan 26, 2024 Friday", "holiday": "Republic Day"},
        {"date": "Jan 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Feb 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Feb 14, 2024 Wednesday", "holiday": "Vasant Panchami"},
        {"date": "Feb 24, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Mar 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Mar 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Mar 25, 2024 Monday", "holiday": "Doljatra"},
        {"date": "Mar 29, 2024 Friday", "holiday": "Good Friday"},
        {"date": "Apr 10, 2024 Wednesday", "holiday": "Idul Fitr"},
        {"date": "Apr 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Apr 14, 2024 Sunday", "holiday": "Bengali New Year"},
        {"date": "Apr 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "May 1, 2024 Wednesday", "holiday": "May Day"},
        {
          "date": "May 8, 2024 Wednesday",
          "holiday": "Guru Rabindranath Jayanti"
        },
        {"date": "May 11, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "May 23, 2024 Thursday", "holiday": "Buddha Purnima"},
        {"date": "May 25, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jun 8, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jun 17, 2024 Monday", "holiday": "Bakrid / Eid al Adha"},
        {"date": "Jun 22, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Jul 13, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Jul 27, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Aug 10, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Aug 15, 2024 Thursday", "holiday": "Independence Day"},
        {"date": "Aug 24, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Sep 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Sep 28, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Oct 2, 2024 Wednesday", "holiday": "Gandhi Jayanti"},
        {"date": "Oct 10, 2024 Thursday", "holiday": "Maha Saptami"},
        {"date": "Oct 11, 2024 Friday", "holiday": "Maha Ashtami"},
        {"date": "Oct 12, 2024 Saturday", "holiday": "Maha Navami"},
        {"date": "Oct 13, 2024 Sunday", "holiday": "Vijaya Dashami"},
        {"date": "Oct 17, 2024 Thursday", "holiday": "Lakshmi Puja"},
        {"date": "Oct 26, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Nov 1, 2024 Friday", "holiday": "Diwali"},
        {"date": "Nov 9, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Nov 15, 2024 Friday", "holiday": "Guru Nanak Jayanti"},
        {"date": "Nov 23, 2024 Saturday", "holiday": "Fourth Saturday"},
        {"date": "Dec 14, 2024 Saturday", "holiday": "Second Saturday"},
        {"date": "Dec 25, 2024 Wednesday", "holiday": "Christmas Day"},
        {"date": "Dec 28, 2024 Saturday", "holiday": "Fourth Saturday"}
      ]
    }
  ]
};
