var epfGuide = {
  "title": "EPF Service Info",
  "epf": [
    {
      "title": "Activate UNA Info",
      "icon": "assets/icons/una.png",
      "desc":
          "→ The Employee Provident Fund (EPF) is an initiative aimed at providing essential social security benefits to employees, fostering stronger bonds between employers and their workforce. To fully embrace these benefits, employers must adhere to a set of regulations and guidelines, with registration as the initial step.\nEmployers are required to furnish the following details for a successful registration:\n→Company name and address\n→Details of the head office and branch offices →Date of the company's incorporation or registration\n→Employee details, including the total workforce\ncoun\n→Description of the company's primary activities, such as manufacturing, production, or services →Legal particulars, including the company's legal structure (e.g., private, public, partnership, society)\n→Owner information, encompassing the roles and addresses of Directors and partners\n→Information\nwage\nregarding employee components, including the total wages disbursed each month\n→Banking details, specifying the bank with which the company holds an account\n→PAN (Permanent Account Number) details\n→Basic employee particulars\nFor online EPF registration, the following documents are typically required:\n→Partnership deed copy for registered partnership firms\n→Certificate of incorporation for Public or Private Limited Companies issued by the Registrar of Companies\n→Registration certificate for societies\n→Memorandum and Articles of Association copy for Public and Private Limited Companies →Rules and objectives of societies for those registered as such\nAll legal documents as required under the Income Tax Act\n→Company's PAN details\n→Partition deed\n→Proof of incorporation, such as the first sales invoice or license issued by competent authorities\n→Employee salary details\n→Balance sheet details\nThese requirements are crucial for the seamless and compliant registration of employers with the EPF, ensuring the provision of social security benefits to employees."
    },
    {
      "title": "Balance (Online) Info",
      "icon": "assets/icons/b_online.png",
      "desc":
          "→ To upload your KYC details to your EPF UAN, follow these step-by-step instructions:\nGo to the EPFO's member portal by visiting http://uanmembers.epfoservices.in/.\nOnce the webpage is displayed, click on Profile in the top bar. From the drop-down menu, select Upload KYC Document.\nAfter clicking that option, choose the specific KYC information you want to update.\nNow, you'll need to upload a scanned self-attested copy of the KYC document. Make sure the document is in either jpg, pdf, or png format, and ensure that the file size does not exceed 300 KB.\nOnce you've uploaded the document, the status of your KYC document will appear as pending. It will only change to approved by employer once your employer verifies and approves it.\nYou'll receive an SMS notification once your employer approves the document.\nAfter this approval, your claim verification process will be expedited, and you can expect faster approvals.\nThe process for embedding KYC details in your EPF UAN is as follows:\nOnce your employer verifies and confirms that the details match and are legitimate, they will digitally attest the document.\n❖The EPFO authorities will then review the approved document for any discrepancies or mismatches.\nIf your document hasn't been approved, you can contact the EPFO helpline at 1800 118 005 or send an email to uanepf@epfindia.gov.in.\nAfter these steps are completed, any future claim verifications will be swift, and your personal KYC details will be securely embedded in the EPF UAN system."
    },
    {
      "title": "Pensioners Info",
      "icon": "assets/icons/pansion.png",
      "desc":
          "→ The Unified Mobile Application for New-age Governance (UMANG) app was introduced in November 2017 to establish a unified platform for accessing various government services. It seamlessly integrates other government initiatives like Aadhaar and Digilocker into a single user-friendly portal.\n→UMANG offers a wide array of over 180 government services, including access to services provided by the Employees' Provident Fund Organization (EPFO). This EPF service on UMANG caters to both employers and employees, enabling them to access and manage their EPF accounts. Through the EPFO tab on the UMANG app, employees can file EPF withdrawal claims and track the status of their claims. To utilize this feature, users are required to have their Aadhaar linked to the app and an active Universal Account Number (UAN).\n→UMANG services are accessible through various channels, including the mobile application, web platform, IVR (Interactive Voice Response), and SMS. This wide accessibility accommodates users with smartphones, feature phones, tablets, and desktop computers. UMANG is designed to bring added convenience to the lives of Indian citizens, leveraging the widespread availability of the internet and smartphones across the country, thus revolutionizing the process of accessing government services."
    },
    {
      "title": "TRRN Status Info",
      "icon": "assets/icons/trrn.png",
      "desc":
          "To\nsubmit\nECR\n(Electronic\nChallan-cum-Return) and process payments, follow these step-by-step instructions:\nStep 1: Log in to the EPFO portal using your ECR portal credentials. After logging in, you can review Establishment Name, Establishment ID, Exemption Status (PF, Pension, EDLI), Establishment Address, and PF office details.\nStep 2: To upload ECR, navigate to the Payments tab and select ECR [UPLOAD].\nStep 3: On the ECR File Upload screen, access the ECR Help File to view the ECR file format. Choose the Wage Month and Salary Disbursal Date for the ECR.\nStep 4: Select your ECR text file for upload. The ECR text file should adhere to the specified format.\nStep 5: Complete the remaining fields, including java.io.File Type (Select ECR), Contribution Rate % (Default value is 12%), and add any necessary comments. Then, click on the Upload button.\nStep 6: Once uploaded, the portal will validate the file against predefined conditions. If the validation is successful, you will receive a Validation Successful message. Click on the Verify button to generate a TRRN (Temporary Return Reference Number).\nStep 7: Generate an ECR summary sheet by clicking on the Prepare Challan button.\nStep 8: On the following screen, adjust values for Total EDLI Contributions (ER Share A/C 21) (if required) and enter Administration & Inspection Charges for Total EPF Charges (A/C 2) and Total EDLI Charges (A/C 22). After making these adjustments, click on the Generate Challan button.\nStep 9: Review the Total Amount on the challan list page, and click on the Finalize icon under Draft Challan List. You can also download Acknowledgment and Receipt Files under In-Process Challan List.\nStep 10: The finalized ECR (Electronic Challan-cum-Receipt) will be available for\nreview.\nStep 11: To proceed with payment, click on the Pay button.\nStep 12: Select the Online payment mode and choose your preferred bank from the list. Click Continue to navigate to the payment gateway for completing the transaction."
    },
    {
      "title": "Claim Info",
      "icon": "assets/icons/claim.png",
      "desc": "→ Here are the steps to follow when applying for an online EPF transfer:\nStep 1: Visit the EPFO website at epfindia.com.\nStep 2: On the homepage, locate the section titled Online Transfer Claim Portal and click on\nit.\nStep 3: Before logging in, check if you are eligible to apply online. If not, you will need to submit a physical copy of Form 13 to either your current or previous employer.\nStep 4: After verifying your eligibility, log in and navigate to the claims section. Select Request for Transfer of Funds.\nStep 5: Form 13 will open. Enter your PF numbers for both your previous and current employers and click on "
          "Click Here to Get Details. The establishment's name and address, the PF account details held by the EPFO, and your name will appear on the screen.\nStep 6: Your date of joining, date of leaving, and father/spouse's name will also be displayed to ensure the correct transfer of funds.\nStep 7: Choose whether you want the claim to be attested by your previous employer or your current employer.\nStep 8: Enter the characters shown in the text box and click on Get PIN. Agree to the declaration in the form by clicking on I Agree.\nStep 9: Enter the PIN received on your registered mobile. The application is then submitted.\nStep 10: A Tracking ID is generated.\nStep 11: Save the form in PDF format, take a printout, sign it, and submit it to your employer within 15 days.\nStep 12: Note the contact details of authorized signatories on the form, which are displayed after submission.\nStep 13: Both your current and previous employers will electronically verify your details. Step 14: Once approval is obtained from both employers, the funds are credited to your EPFO account by the EPFO branch office.\nStep 15: The employer plays a crucial role in this process by verifying the authenticity and signature of the employee.\nThe EPFO keeps you informed through SMS notifications, and you can also track the application's progress on the EPFO website."
    },
    {
      "title": "Balance Call Info",
      "icon": "assets/icons/phone-call.png",
      "desc":
          "Introducing our EPF Call Info feature, designed to provide you with seamless access to your Employees' Provident Fund (EPF) balance at your fingertips. With this user-friendly functionality, you can effortlessly stay updated on your financial savings, empowering you to make informed decisions about your future.\n\nTo utilize this service, simply give a missed call to our dedicated EPF Call Info number from your registered mobile number. Within moments, you will receive a detailed SMS containing your current EPF balance, contribution details, and transaction history. This quick and convenient method ensures that you have real-time access to your provident fund information without the need for extensive navigation.\n\nOur commitment to your financial well-being extends beyond just providing numbers; we aim to deliver a holistic experience. In addition to the EPF balance, the SMS update includes valuable insights into your contribution trends, helping you understand your financial growth over time.\n\nThis feature is especially beneficial for those on the move, enabling you to check your EPF balance wherever and whenever it's most convenient for you. Whether you're planning for a major life event, considering an investment, or simply want to keep track of your financial health, the EPF Call Info feature is your go-to tool.\n\nFor further assistance or to address any queries, our dedicated customer support team is readily available to assist you. We understand the importance of financial transparency, and our EPF Call Info service is designed to provide you with the information you need in a secure and efficient manner.\n\nEmpower yourself with knowledge, take control of your financial future, and experience the convenience of our EPF Call Info feature – because your financial well-being matters to us."
    },
    {
      "title": "Balance (SMS) Info",
      "icon": "assets/icons/sms.png",
      "desc":
          "Embark on a journey of financial empowerment with our state-of-the-art EPF Balance (SMS) service, designed to redefine the way you stay connected with your provident fund. Seamlessly bridging the gap between information and accessibility, this innovative service allows you to effortlessly retrieve real-time updates about your Employees' Provident Fund (EPF) via a simple text message. By sending your Universal Account Number (UAN) to our designated SMS number, you unlock a treasure trove of financial insights at your fingertips.\n\nIn a world where time is of the essence, our EPF Balance (SMS) service stands as a beacon of efficiency, delivering comprehensive details including your current EPF balance, recent contributions, and a snapshot of your transaction history - all encapsulated in the convenience of an SMS. Gone are the days of tedious logins and complex navigations; now, a single SMS opens the gateway to financial clarity.\n\nNavigating through life's uncertainties becomes a breeze as you receive timely updates on your EPF savings, fostering a sense of control over your financial destiny. Our commitment to security is unwavering - rest assured that your personal and financial information is safeguarded through advanced encryption protocols, ensuring a worry-free experience.\n\nImagine the power of financial planning literally in the palm of your hand. With our EPF Balance (SMS) service, you not only gain access to numerical data but also receive personalized insights and trends, empowering you to make informed decisions about your financial future. As we believe in transparency, each SMS is crafted to be a beacon of clarity, eliminating ambiguity and demystifying the complexities of provident fund management.\n\nFor those always on the move, our EPF Balance (SMS) service becomes an invaluable companion, allowing you to check your EPF balance anytime, anywhere. Whether you're planning for a major life event, contemplating an investment, or simply staying vigilant about your financial health, our SMS service is the compass guiding you through the labyrinth of financial intricacies.\n\nOur customer-centric approach extends beyond technology - a dedicated support team is at your beck and call to address any queries, ensuring that you embark on this financial journey with confidence. Your financial well-being is our top priority, and our EPF Balance (SMS) service is not just a service; it's a commitment to empowering you with the tools you need for a secure and prosperous future.\n\nIn conclusion, embrace the future of financial management with our EPF Balance (SMS) service - where simplicity meets sophistication, and information meets accessibility."
    },
    {
      "title": "FAQ Info",
      "icon": "assets/icons/faq.png",
      "desc":
          "Our Frequently Asked Questions (FAQ) service serves as your personal guide through the intricate landscape of EPF, addressing a wide array of common queries to empower you with the knowledge needed for informed decision-making.\n\nEver wondered about the specifics of EPF contributions, the intricacies of withdrawal processes, or the significance of your Universal Account Number (UAN)? Look no further – our FAQ service is meticulously curated to provide detailed answers to these questions and more. Delve into a wealth of information that covers every aspect of your EPF journey, from understanding the calculation of provident fund contributions to exploring the diverse investment options available.\n\nAccessible 24/7, our FAQ service ensures that you have instant and convenient access to a reservoir of knowledge whenever you need it. Whether you're a seasoned EPF participant or navigating the landscape for the first time, our detailed responses guide you through the labyrinth of EPF intricacies, fostering financial literacy and confidence.\n\nAs we understand that each individual's financial journey is unique, our FAQ service is designed to cater to a diverse range of queries. From the eligibility criteria for EPF membership to the documentation required for withdrawals, our service leaves no stone unturned in providing the clarity you seek. Furthermore, our commitment to staying updated with the latest EPF regulations ensures that our FAQ service evolves alongside the dynamic landscape of provident fund management.\n\nConsider our FAQ service your trusted companion, always ready to address your questions and concerns. We recognize that navigating the world of EPF can be daunting, and our detailed responses aim to simplify the process, making your financial journey more comprehensible and manageable.\n\nIn a world where information is key, our FAQ service strives to empower you with the insights necessary to make well-informed decisions regarding your financial future. Experience the confidence that comes with knowledge by exploring the in-depth answers and guidance provided by our dedicated FAQ service, your gateway to unlocking the full potential of your EPF journey.\nplease visit"
    },
    {
      "title": "Locate Office Info",
      "icon": "assets/icons/locate_office.png",
      "desc":
          "Embark on a seamless journey to locate Employees' Provident Fund (EPF) offices with our dedicated 'Locate Office' service, designed to simplify the process of finding EPF offices near you. Whether you're a beneficiary seeking assistance or an EPF member looking to resolve queries in person, our service acts as your virtual compass, guiding you to the nearest EPF office with ease and efficiency.\n\nUtilizing cutting-edge geolocation technology, our 'Locate Office' service provides precise coordinates and detailed directions to the nearest EPF office based on your current location. Simply input your address or enable location services, and our intuitive interface will display a comprehensive list of EPF offices in your vicinity, complete with contact details and operational hours.\n\nWe understand that accessibility is paramount when it comes to availing EPF services, which is why our 'Locate Office' service prioritizes convenience and efficiency. Whether you're in a bustling metropolitan area or a remote locality, our service ensures that you can easily identify the closest EPF office, eliminating the need for guesswork or extensive research.\n\nFurthermore, our service goes beyond merely providing directions – it also offers valuable insights into the services offered at each EPF office, enabling you to plan your visit accordingly. Whether you're seeking assistance with EPF account management, documentation submission, or resolving grievances, our service equips you with the information needed to make the most of your visit.\n\nIn addition to enhancing accessibility, our 'Locate Office' service emphasizes transparency and reliability. Each EPF office listed undergoes regular verification to ensure accuracy, so you can trust that the information provided is up-to-date and reliable. Furthermore, our user-friendly interface makes navigating the service effortless, catering to users of all proficiency levels.\n\nEmpower yourself with the convenience of our 'Locate Office' service and experience a hassle-free approach to accessing EPF services. Whether you're a seasoned EPF participant or exploring the benefits of provident fund membership for the first time, our service simplifies the process of locating EPF offices, ensuring that assistance is always within reach.\n\nExperience the peace of mind that comes with knowing you can easily locate an EPF office whenever the need arises. With our 'Locate Office' service, navigating the landscape of EPF services has never been more straightforward – empowering you to take control of your financial future with confidence and ease."
    },
    {
      "title": "Help Line Info",
      "icon": "assets/icons/helpLine.png",
      "desc":
          "Discover unparalleled support through our dedicated 'Help Line' service, meticulously designed to provide immediate assistance and guidance for all your Employees' Provident Fund (EPF) queries. Our helpline acts as your lifeline to expert assistance, ensuring that you have access to timely and reliable information, empowering you to navigate the complexities of EPF with confidence.\n\nThe 'Help Line' service operates around the clock, staffed by a team of knowledgeable and friendly professionals ready to address your EPF-related concerns. Whether you're seeking clarification on account details, guidance on the EPF withdrawal process, or assistance with any other aspect of provident fund management, our helpline is committed to providing comprehensive and personalized support tailored to your needs.\n\nTo access our 'Help Line' service, simply dial the designated toll-free number, and you'll be greeted by our customer support team. Our interactive voice response system and skilled representatives ensure that you are swiftly directed to the relevant information or connected with an expert who can provide detailed assistance. Your queries are our priority, and our helpline is dedicated to ensuring that you receive the guidance you need in a clear and concise manner.\n\nOur commitment to transparency extends to our helpline service, where you can expect accurate and up-to-date information regarding EPF policies, regulations, and procedures. Whether you're a new EPF member or a seasoned participant, our helpline serves as a valuable resource for obtaining insights into the latest updates and best practices for managing your provident fund effectively.\n\nBeyond mere information dissemination, our 'Help Line' service strives to create a supportive and empowering experience for users. We understand that each individual's financial journey is unique, and our helpline is equipped to handle a diverse range of queries, ensuring that you receive personalized assistance tailored to your specific circumstances.\n\nExperience the peace of mind that comes with knowing you have a reliable 'Help Line' at your fingertips, ready to guide you through any challenges or uncertainties related to EPF. Our commitment to excellence is reflected in the quality of service you'll receive, making our 'Help Line' an indispensable tool for those seeking expert guidance on their provident fund journey.\n\nAs we continuously strive to enhance our services, your feedback is invaluable. Our 'Help Line' is not just a point of contact; it's a partnership in your journey towards financial well-being. Dial in and experience the difference today.\n\n"
    }
  ]
};
