var insurance = {
  "insurance": [
    {
      "title": "Life Insurance Info",
      "icon": "assets/icons/life.png",
      "description":
          "Life insurance constitutes an agreement between a policy owner and a life insurance company. It involves a policy that assures the payment of a specified sum to one or more designated beneficiaries upon the demise of the insured individual. This payout is in exchange for the premiums made by the policyholder over the course of their lifetime.\nTypes of Life Insurance\nNumerous life insurance options cater to a wide range of preferences and requirements. When determining the most suitable coverage, its crucial to weigh the decision between temporary and permanent life insurance, depending on the insured individuals short- or long-term needs.\nPermanent Life Insurance\nPermanent life insurance remains in effect throughout the insured persons lifetime, unless the policyholder discontinues premium payments or chooses to surrender the policy. It typically carries a higher cost compared to term life insurance. Whole life insurance, a subset of permanent life insurance, builds a cash value that is designed to endure for the lifetime of the insured. Cash-value life insurance also grants policyholders the flexibility to utilize the accrued cash value for various purposes, including obtaining loans, accessing cash, or covering policy premiums.\nUniversal life (UL) insurance is a form of permanent life insurance incorporating a cash value component that accrues interest. One distinctive aspect of universal life insurance is its premium flexibility, allowing policyholders to modify premiums over time and select either a consistent death benefit or one that grows over time, unlike term and whole life insurance policies.\nIndexed universal life (IUL) is a variant of universal life insurance that grants policyholders the opportunity to accumulate a fixed or equity-indexed rate of return on the cash value component."
    },
    {
      "title": "Health Insurance Info",
      "icon": "assets/icons/health.png",
      "description":
          "Health insurance is a form of insurance designed to provide coverage for medical expenses incurred as a result of illness. These expenses encompass various aspects, including hospitalization costs, medication expenses, and fees for doctor consultations.\nHealth insurance policies in the United States typically include exemptions or exclusions from coverage, such as:\nHow Health Insurance Works\nNavigating health insurance in the United States can be quite intricate. Its an industry marked by numerous regional and national competitors, each offering varying coverage, pricing, and availability that can differ not only from state to state but even within counties. Approximately half of Americans access health insurance through their employment, with the employer often contributing to the premiums. Importantly, the cost borne by the employer is tax-deductible, and the benefits to the employee are typically tax-free, though certain exceptions apply, especially for S corporation employees.For self-employed individuals, freelancers, and gig workers, the option to purchase insurance directly is available. The Affordable Care Act of 2010, commonly known as Obamacare, played a pivotal role by mandating the creation of a national database called HealthCare.gov. This platform enables individuals to explore standardized insurance plans offered by private insurers in their locality. Additionally, subsidies are provided to offset the coverage costs for taxpayers whose incomes fall below the federal poverty threshold.\nCertain states have established their own iterations of HealthCare.gov, customized to serve the unique requirements of their residents. However, its important to note that not all states have adopted such state-specific platforms."
    },
    {
      "title": "Home Insurance Info",
      "icon": "assets/icons/home_i.png",
      "description":
          "Homeowners insurance is a type of property insurance that safeguards an individuals dwelling, as well as the contents and possessions within the home. Additionally, homeowners insurance offers liability protection in cases of accidents occurring within the home or on the property.\nUnderstanding Homeowners Insurance\nA typical homeowners insurance policy provides coverage for four primary categories of incidents on the insured property: interior damage, exterior damage, loss or damage to personal belongings, and injuries that occur on the property. In the event of a claim related to any of these incidents, the homeowner is responsible for covering a deductible, which represents their out-of-pocket expenses as per the insurance policy.For example, if a homeowner files a claim for interior water damage that amounts to an estimated \$10,000 in repair costs, as determined by a claims adjuster, and the policy specifies a \$4,000 deductible, the homeowner will be notified of this deductible amount, which they are responsible for according to the policy agreement. Subsequently, the insurance company will disburse a payment covering the remaining cost, in this case, \$6,000. Its worth noting that the deductible amount has an inverse relationship with the homeowners insurance premium; a higher deductible corresponds to a lower monthly or annual premium for the policy.\nHomeowners Insurance vs. Mortgage Insurance\nHomeowners insurance and mortgage insurance are distinct entities. Typically, mortgage insurance is a requirement imposed by the bank or mortgage company, applicable to homebuyers who put down a down payment of less than 20% of the propertys cost. This condition also extends to those obtaining an FHA loan, as the Federal Housing Administration mandates mortgage insurance in such cases."
    },
    {
      "title": "Bicycle Insurance Info",
      "icon": "assets/icons/bicycle.png",
      "description":
          "Cycle insurance provides financial protection in the event of damage or loss to the insured bicycle resulting from accidents or theft. Additionally, it incorporates personal accident coverage to safeguard the cyclist in case of injury.\nWhile bicycle insurance can be a prudent choice for certain individuals, its important to consider that other existing insurance policies might already offer sufficient coverage for both you and your bike. For instance, in situations where your bike is stolen or you sustain an injury in an accident, your homeowners or renters insurance policy could potentially provide the necessary coverage.\nBelow are some situations in which you'd be covered by other insurance, like home, renters or auto.\nas\nIf your bicycle sustains damage or gets stolen, you may find coverage under your personal property insurance, typically included a standard component of your renters or homeowners insurance policy. This coverage will reimburse you up to the predetermined coverage limit, with your deductible subtracted.Its important to note that personal property coverage often comes with sublimits. These sublimits establish a maximum amount that your insurance will pay for specific valuable items such as jewelry, antiques, or expensive furs. It is advisable to review the sublimit applicable to your bicycle to ascertain whether it would receive full coverage in case of damage or theft. If you find that your coverage limit is insufficient, some insurers might offer the option to schedule your bicycle, which entails increasing coverage explicitly for your bike."
    },
    {
      "title": "Disability Insurance Info",
      "icon": "assets/icons/disability.png",
      "description":
          "Disability claim means a request for benefits under a plan in which the applicant must demonstrate a disability and the plan\nadministrator will determine the disability in order for the applicant to receive benefits. Temporary impairment is an income adjustment benefit that provides a percentage. weekly pre-disability benefits when employees are not working due to a disability claim. It usually covers accidents and illnesses that employers would not cover."
    }
  ]
};
